resourcePackages:
- eu.internetofus.wenet_task_manager.api
prettyPrint: true
cacheTTL: 0
openAPI:
  tags:
    - name: Tasks
      description: The functionality provided allows to manage the tasks.
    - name: Task Types
      description: The functionality provided allows to manage the task types.
    - name: Task Transactions
      description: The functionality provided allows to modify a task by a transaction.
    - name: Norms
      description: The functionality provided allows to manage the norms of a component.
    - name: Other
      description: Other services provided by the API.
  info:
    # The verion of the API has to be synchonized with the 'api-version' property of the 'pom.xml'
    version: '1.0.0'
    title: WeNet - Task manager API
    description:  >-
      The task manager component is the one responsible for storing and maintaining
      the task and task types. The task types define the interaction protocols between users
      and the task is an instance of this type.

      The task type uses the [OpenAPI](https://swagger.io/specification/) to define
      the possible attributes of a task, the actions or transactions that a user can do
      in a task, and the messages or callbacks that can be posted to the application
      from the task execution. Also, it has a set of norms that describe the behaviour
      of the user on the task execution.

      When a set of users want to be coordinated to do something one of them create a new task.
      This task has associated a type that describes the behaviour of the user on this execution.
      The creator of the task, if wants, can define new norms that can modify this default
      behaviour. The task manager is also responsible for maintaining the state of this task execution.
      For this reason on the task model are stored all the transactions that have been done
      on it, and on this transaction are stored the messages that has been sent to the application
      when this transaction is executed. As well, it provides services that can be used
      to obtain the messages sent to the users by the application callbacks.
    contact:
      name: Bruno Rosell i Gui (UDT-IA, IIIA-CSIC)
      email: rosell@iiia.csic.es
    license:
      name: Apache V2
      url: http://www.apache.org/licenses/LICENSE-2.0
  servers:
    - url: https://internetofus.u-hopper.com/prod/task_manager
      description: Production instance
    - url: https://wenet.u-hopper.com/dev/task_manager
      description: Staging instance
    - url: https://ardid.iiia.csic.es/wenet/task-manager
      description: IIIA development server
