resourcePackages:
- eu.internetofus.wenet_task_manager.api
prettyPrint: true
cacheTTL: 0
openAPI:
  tags:
    - name: Other
      description: Other services provided by the API.
    - name: Tasks
      description: The functionality provided allows to access the user task.
  info:
    # The verion of the API has to be synchonized with the 'api-version' property of the 'pom.xml'
    version: '0.2.0'
    title: WeNet - Task manager API
    description:  >-
      This API will be used to storing and maintaining the WeNet user task.
    contact:
      name: Bruno Rosell i Gui (UDT-IA, IIIA-CSIC)
      email: rosell (at) iiia.csic.es
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
  servers:
    - url: http://ardid.iiia.csic.es/wenet-task-manager/0.2.0/
      description: Testing server
