resourcePackages:
- eu.internetofus.wenet_task_manager.api
prettyPrint: true
cacheTTL: 0
openAPI:
  tags:
    - name: Other
      description: Other services provided by the API.
    - name: Tasks
      description: The functionality provided allows to access the user task.
  info:
    # The verion of the API has to be synchonized with the 'api-version' property of the 'pom.xml'
    version: '0.3.0'
    title: WeNet - Task manager API
    description:  >-
      This API will be used to storing and maintaining the WeNet user task.
      The task is associated to the next concepts:

         * **TaskType**: describe the attributes and norms that describe the generic goal of a task.
         * **Task**: the instance of a task type that is active.
         * **TaskView**: maintains the state of the task instance from the point of view of an specific user.

    contact:
      name: Bruno Rosell i Gui (UDT-IA, IIIA-CSIC)
      email: rosell (at) iiia.csic.es
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
  servers:
    - url: https://wenet.u-hopper.com/task_manager
      description: WeNet production server
    - url: https://wenet.u-hopper.com/dev/task_manager
      description: WeNet development server server
    - url: http://ardid.iiia.csic.es/wenet/task-manager/0.3.0/
      description: IIIA development Testing
